language: node_js
node_js:
  - "6"
sudo: false
cache: yarn
branches:
  only:
    - master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
  chrome: stable
install:
  - yarn --no-lockfile
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --window-size=430,430
script:
  - yarn test
after_success:
  - yarn build